# config.yaml

# Digital Twin Model Description
model: 
  name: Simply Supported Beam
  type: Physical Based
  domain: Structural
  3d_vis: True

# List of operations to perform
available_operations: 
  displacement:
    tbrom: SSB_6_Def1
    tbrom_units: mm
    suboperations: [ux, uy, uz, norm]    
    suboperations_units: mm
  stress:
    tbrom: SSB_6_Str1
    tbrom_units: MPa
    suboperations: [von_mises, xx, yy, zz, xy, yz, xz]
    suboperations_units: MPa
  fatigue:
    tbrom: SSB_6_Str1
    tbrom_units: MPa
    suboperations: [cycle, damage]
    suboperations_units: [cycles, None]
    derived: True
    script: fatigue.py

# Twin files
twin_files:
  - data/raw/twin_file_dsp.twin
  - data/raw/twin_file_str.twin

available_named_selections:
  - All_Body
  - Frame
  - Weld
available_deformation_scales:
  - Undeformed
  - True Scale
  - 0.5 Auto
  - Auto Scale
  - 2x Auto
  - 5x Auto
available_output_formats:
  - gltf
  - vrml
  - obj

# Parameters
inputs:
   Force_Magnitude:
    initial_value: 3000
    unit: 'N'
    minimum_value: 2900
    maximum_value: 5000
outputs:
autoscale: 8.5