# config.yaml

# Digital Twin Project 
Model: 
  name: Simply Supported Beam
  type: Physical Based
  domain: Structural
  3d_vis: True

# List of operations to perform
available_operations: 
  displacement:
    tbrom: SSB_6_Def1
    units: mm
    suboperations: [ux, uy, uz, norm]    
  stress:
    tbrom: SSB_6_Str1
    units: MPa
    suboperations: [von_mises, xx, yy, zz, xy, yz, xz]
  fatigue:
    tbrom: SSB_6_Str1
    units: MPa
    suboperations: [cycle, damage]
    derived: True
    script: fatigue.py

# Twin files
twin_files:
  - data/raw/twin_file_dsp.twin
  - data/raw/twin_file_str.twin

availabe_named_selections:
  All_Body
  Frame
  Weld
available_deformation_scales:
  Undeformed
  True Scale
  0.5 Auto
  Auto Scale
  2x Auto
  5x Auto
operation_units:
  displacement: mm
  stress: MPa
  fatigue:
    cycle: cycles
    damage: 
available_roms: [0]

# Parameters
inputs:
   Force_Magnitude:
    initial_value: 3000
    unit: 'N'
    minimum_value: 2900
    maximum_value: 5000
outputs:
autoscale: 8.5