# config.yaml

# Directory paths
input_dir: 'data/input/'
output_dir: 'data/output/'
twin_file: 'data/raw/twin_disp_file.twin'
rst_file: 'data/raw/file.rst'
twin_disp_file: 'data/raw/twin_disp_file.twin'

# List of operations to perform
available_operations:
  - displacement:
    - ux
    - uy
    - uz
    - norm
  - stress:
    - von_mises
    - xx
    - yy
    - zz
    - xy
    - yz
    - xz
  - fatigue:
    - cycle
    - damage

operation: 
  - displacement
  - norm

# Other configuration settings (example)
mesh_settings:
  show_edges: True
  format: 'gltf'

# Parameters
inputs:
  - Force_Magnitude:
    - initial_value: 4000
    - unit: 'N'
    - minimum_value: 0
    - maximum_value: 10000
outputs:
initial_value:
  - Force_Magnitude: 4000
named_selections:
  - Frame
  - Weld
scoping: frame
autoscale: 200
deflection: 1