# config.yaml

# Directory paths
input_dir: 'data/input/'
output_dir: 'data/output/'
twin_file: 'data/raw/twin_disp_file.twin'
rst_file: 'data/raw/model.rst'
twin_disp_file: 'data/raw/twin_disp_file.twin'

# List of operations to perform
operations:
  - displacement
  - stress
  - damage

# Other configuration settings (example)
mesh_settings:
  show_edges: True
  format: 'gltf'

# Parameters
inputs:
  - Force_Magnitude
outputs:
initial_value:
  - Force_Magnitude: 3000

named_selections:
  - Frame
  - Weld
autoscale: 200
deflection: 1